apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cattle-go
  janus-idp.io/tekton: cattle-go
  backstage.io/kubernetes-id: cattle-go
  backstage.io/kubernetes-namespace: rhtap-test-organization-jk 
  app.kubernetes.io/part-of: cattle-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
